language: minimal
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
after_success:
  - ls -a
  - pandoc --from markdown_github --to html SUMMARY.md --output SUMMARY.html
  - cat SUMMARY.html
